alias ,as='just -g add-and-squash-fix'
alias asciinema='uvx asciinema'
alias ,homeconfig='$EDITOR $HOME/.config/home-manager/home.nix'
alias ,ir='just -g interactive-rebase'
alias nix='noglob nix'
alias ,zshconfig='$EDITOR $HOME/.zshrc'
