#!/usr/bin/env bash
# curl-pipe remote yadm and bootstrap dotfile repo
# See bootstrap.yadm.io
# yadm_repo="https://github.com/TheLocehiliosan/yadm"
# yadm_release=${release:-master}
# repo_url="https://github.com/stephan-koenig/config.git"

# curl -fsSL "$yadm_repo/raw/$yadm_release/yadm" | bash -s -- clone "$repo_url" -f

# Setup script for setting up a new macOS machine
echo 'Starting setup'

cd $HOME

# Install Homebrew if missing (will also install Xcode command line tools)
if test ! "$(which brew)"; then
  echo 'Installing Homebrew...'
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

echo 'Installing Homebrew packages, casks and Mac App Store Apps...'
brew bundle --file=~/.config/brew/Brewfile

# Force links
# brew link --force <package>

echo 'Cleaning up Homebrew...'
brew cleanup

# 1Password SSH agent setup
mkdir -p ~/.1password
ln -s ~/Library/Group\ Containers/2BUA8C4S2C.com.1password/t/agent.sock ~/.1password/agent.sock

# GPG setup
echo 'Importing GPG public key...'
gpg --auto-key-locate hkps://keys.openpgp.org --locate-keys stephan.koenig@gmail.com
echo 'You must first trust your key on your YubiKey using "gpg --edit-key <key id>",'
echo 'then "trust" and "5" (for ultimate) to sign with it.'
echo 'Ensure the latest "gpg-agent" is running using "gpgconf --kill all".'

# zsh setup
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

echo 'Copying configuration and preference files into place...'

# Link zsh configuration files
for file in "$HOME/.config/zsh/"*; do
  link="${ZSH_CUSTOM}/$(basename "${file}")"
  if [[ ! -f "$link" ]]; then
    ln -s "${file}" "${link}"
  fi
done

echo 'Installing R packages and Miniconda...'
Rscript $HOME/.R/setup_R.R

# TODO: Manual install reminders
# Poll everywhere https://www.polleverywhere.com/
