#!/usr/bin/env bash

# # curl-pipe remote yadm and bootstrap dotfile repo
# # See bootstrap.yadm.io
# yadm_repo="https://github.com/TheLocehiliosan/yadm"
# yadm_release=${release:-master}
# repo_url="https://github.com/stephan-koenig/config.git"
# curl -fsSL "$yadm_repo/raw/$yadm_release/yadm" | bash -s -- clone "$repo_url" -f

# Setup script for a new macOS machine
echo 'Starting setup'

cd $HOME

# # Determinate Nix installer
# echo 'Installing Nix...'
# curl --proto '=https' --tlsv1.2 -sSf -L \
#   https://install.determinate.systems/nix \
#   | sh -s -- install macos

# echo 'Clone dotflile repository with yadm...'
# repo_url="https://github.com/stephan-koenig/config.git"
# nix run nixpkgs#yadm -- clone "${repo_url}" -f

# echo 'Installing Nix Home Manager...'
# nix run home-manager/master -- init --switch

# echo 'Installing Nix packages...'
# nix flake update --flake $HOME/.config/home-manager && home-manager switch

# Install Homebrew if missing (will also install Xcode command line tools)
if test ! "$(which brew)"; then
  echo 'Installing Homebrew...'
  NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

echo 'Installing Homebrew packages, casks and Mac App Store Apps...'
brew bundle --file=~/.config/brew/Brewfile

# Force links
# brew link --force <package>

echo 'Cleaning up Homebrew...'
brew cleanup

# Make brew available to macOS GUI apps
# https://docs.brew.sh/FAQ#my-mac-apps-dont-find-homebrew-utilities
# # sudo launchctl config user path "$(brew --prefix)/bin:${PATH}"

echo 'Installing zsh plugins...'
antidote load

# 1Password SSH agent setup
mkdir -p ~/.1password
ln -s ~/Library/Group\ Containers/2BUA8C4S2C.com.1password/t/agent.sock ~/.1password/agent.sock

# # GPG setup
# echo 'Importing GPG public key...'
# gpg --auto-key-locate hkps://keys.openpgp.org --locate-keys stephan.koenig@gmail.com
# echo 'You must first trust your key on your YubiKey using "gpg --edit-key <key id>",'
# echo 'then "trust" and "5" (for ultimate) to sign with it.'
# echo 'Ensure the latest "gpg-agent" is running using "gpgconf --kill all".'

echo 'Installing R and R packages...'
rig add --without-cran-mirror && rig system setup-user-lib
Rscript $HOME/.R/setup_R.R

echo 'Installing GitHub CLI and Quarto extensions...'
gh extension install github/gh-copilot
gh extension install github/gh-classroom
quarto install tinytex
quarto install chrome-headless-shell

echo 'Installing Python tools...'
uv tool install ruff
uv tool install marimo

# TODO: Manual install reminders
# Poll everywhere https://www.polleverywhere.com/
