#!/usr/bin/env bash
# Setup script for setting up a new macOS machine
echo 'Starting setup'

# Clone dotfiles
git clone https://github.com/stephan-koenig/config.git

echo 'Installing command line tools...'
xcode-select --install

# Install Homebrew if missing
if test ! "$(which brew)"; then
  echo 'Installing Homebrew...'
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

echo 'Installing Homebrew packages, casks and Mac App Store Apps...'
brew bundle 

# Force links
# brew link --force <package>

echo 'Cleaning up Homebrew...'
brew cleanup

# yadm setup
yadm clone https://github.com/stephan-koenig/config.git

# zsh setup
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k"

echo 'Copying configuration and preference files into place...'

# Link zsh configuation files
for file in "$HOME/.config/zsh/"*; do
  link="${ZSH_CUSTOM}/$(basename "${file}")"
  if [[ ! -f "$link" ]]; then
    ln -s "${file}" "${link}"
  fi
done

echo 'Installing Miniconda...'
curl -sL \
  'https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh' > \
  'Miniconda3.sh'
bash 'Miniconda3.sh'
rm 'Miniconda3.sh'

# Create a conda environment
# echo 'Setting up conda environments...'
# curl -sL \
#   'https://data.qiime2.org/distro/core/qiime2-2020.8-py36-osx-conda.yml' > \
#   'qiime2.yml'
# conda env create -n 'qiime2' --file 'qiime2.yml'
# rm 'qiime2.yml'

# TODO: R packages
# TODO: Manual install reminders
# Poll everywhere https://www.polleverywhere.com/